nation3/nationcred-contracts

contracts/INationCred.sol
https://app.dework.xyz/nation3/nationcred-p?taskId=32c456fd-9a2d-4d45-b93b-a580657744df
closes #28
=> Add NationCred interface (#28)

.env.example, README.md, hardhat.config.ts
Prepare for deployment to Goerli testnet
https://app.dework.xyz/nation3/nationcred-p/view/board-l58b1zlf?taskId=4cbe90c2-fd06-43a2-aaaa-c9cd5a84ef84
=> chore: prepare for deployment to goerli testnet

README.md, contracts/GitHub.sol, scripts/deploy-github.ts, test/GitHub.ts
Add GitHub smart contract as the link between the Citizen Directory and SourceCred.
https://app.dework.xyz/nation3/nationcred-p/view/board-l58b1zlf?taskId=575acb44-2a55-4f71-8789-1ecef10d496a
closes #3
```shell
REPORT_GAS=true npx hardhat test
```
```javascript
GitHub
constructor
username: aahna-ashina
✓ Deploy contract
constructor
owner.address: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
updateUsername
usernameAfterUpdate: test
✓ updateUsername
Greeter
Deploying a Greeter with greeting: Hello, world!
Changing greeting from 'Hello, world!' to 'Hola, mundo!'
✓ Should return the new greeting once it's changed
·-------------------------------|----------------------------|-------------|-----------------------------·
|     Solc version: 0.8.17      ·  Optimizer enabled: false  ·  Runs: 200  · …
```
=> Add GitHub smart contract #3

.env.example, README.md, hardhat.config.ts
Deploy GitHub smart contract to Goerli/Mainnet
https://app.dework.xyz/nation3/nationcred-p/view/board-l58b1zlf?taskId=bae3ca08-b9a4-4394-9e16-6d3bbaeb5c99
=> chore: deploy github contract to mainnet

README.md, contracts/Discord.sol, scripts/deploy-discord.ts, test/Discord.ts
https://app.dework.xyz/nation3/nationcred-p/view/board-l58b1zlf?taskId=8ffcb758-6331-4c17-a689-0460195cd002
closes #19
=> feat: add discord smart contract (#19)

contracts/Discourse.sol, test/Discourse.ts
https://app.dework.xyz/nation3/develop-1?taskId=cc2851fd-4b93-4356-a0c8-3dcc8a08d668
https://github.com/nation3/nationcred-contracts/issues/20
This is pretty much a copy of the Discord.sol smart contract which is super simple and has already been tested.
=> Add Discourse contract & tests

README.md, scripts/deploy-discourse.ts
https://etherscan.io/tx/0x1cd28a3cd373ee771bf679763a8f0d333e1a9e3b8278be2df2300dc37c07f4c9
#20
=> chore: deploy discourse contract to mainnet (#20)

.env.example, .github/codecov.yml, .github/workflows/unit_tests.yml, README.md, contracts/INationCred.sol, contracts/NationCred.sol, hardhat.config.ts, scripts/deploy-nationcred.ts, test/ NationCred.ts, test/NationCred.ts
closes #24
- Copied an array of active passportIDs from https://github.com/nation3/nationcred-datasets/blob/main/nationcred/output/nationcred-active-citizens.csv
- <img width="1221" alt="Screenshot 2023-03-23 at 4 31 15 PM" src="https://user-images.githubusercontent.com/95955389/227146670-9c3d2935-ac47-4679-84c6-5f9530298b3a.png">
https://sepolia.etherscan.io/tx/0xb68bd231719c951da20e6368d290addefbff2d171ef65b8dcefd25d5d3459489
- 75,148 gas for for setting 5 active citizens:  https://sepolia.etherscan.io/tx/0x56752402c1f562083a5e131a92e126bd2a9b82e654793b87a50c6191db3c5307
- 41,524 gas for setting 8 active citizens:  https://sepolia.etherscan.io/tx/0xfb7d1c9e55ce791f9dbd1ef6385a40e2046fafa5908421baf6d2cf0719f4e116
- 47,030 gas for setting 25 active citizens: …
=> Add NationCred smart contract (#24)

contracts/utils/IPassportUtils.sol, contracts/utils/PassportUtils.sol, package-lock.json, package.json, test/PassportUtils.ts
https://app.dework.xyz/nation3/development-guild-43499?taskId=71dc858b-50e8-4561-ad03-6bcbb885d5cc
#72
=> Return zero when locked amount lower than threshold

README.md, contracts/GitHubUsernames.sol, contracts/NationCred.sol, contracts/citizens/DeveloperSkillLevels.sol, contracts/mock/PassportIssuerMock.sol, contracts/passport/IPassportIssuer.sol, contracts/utils/IPassportUtils.sol, contracts/utils/PassportUtils.sol, package-lock.json, package.json, scripts/deploy-developer-skills.ts, scripts/deploy-nationcred.ts, test/DeveloperSkillLevels.ts, test/PassportUtils.ts
https://app.dework.xyz/nation3/development-guild-43499?taskId=6263bce8-c63f-4b7b-a3c7-c1a707213d96
close #82
- https://goerli.etherscan.io/address/0xd99884fE5d9aCE5ECa73Dd5D4c0fe123F1560B7B#code
- https://goerli.etherscan.io/tx/0x20c2646da388664b248e6c112deda42b61c2b6845b628c310f4fd6018ee6b375
=> Add smart contract for storing skill level ratings per citizen role

README.md, contracts/GitHubUsernames.sol, contracts/NationCred.sol, contracts/citizens/DeveloperSkillLevels.sol, contracts/citizens/OperatorSkillLevels.sol, contracts/utils/PassportUtils.sol, package-lock.json, package.json, scripts/deploy-developer-skill-levels.ts, scripts/deploy-github-usernames.ts, scripts/deploy-operator-skill-levels.ts, scripts/deploy-passport-utils.ts, test/DeveloperSkillLevels.ts, test/OperatorSkillLevels.ts
#82
https://goerli.etherscan.io/address/0xfB9deD3Aa0B4A3A53c16D959aaEAbacD37c23eF7#code
=> Operator skill levels

README.md, contracts/citizens/MarketeerSkillLevels.sol, contracts/mock/PassportIssuerMock.sol, contracts/mock/VotingEscrowMock.sol, scripts/deploy-marketeer-skill-levels.ts, test/DeveloperSkillLevels.ts, test/MarketeerSkillLevels.ts, test/OperatorSkillLevels.ts, test/PassportUtils.ts
close #82
https://goerli.etherscan.io/address/0xdf691B0948AdaA27F44B390055E162B1466d6cc8#code
=> Marketeer skill levels (#82)

README.md, contracts/mock/ERC20Mock.sol, contracts/rewards/DevGuildRewardsDistributor.sol, contracts/rewards/OpsGuildRewardsDistributor.sol, scripts/deploy-developer-skill-levels.ts, scripts/deploy-discord.ts, scripts/deploy-discourse.ts, scripts/deploy-github-usernames.ts, scripts/deploy-marketeer-skill-levels.ts, scripts/deploy-nationcred.ts, scripts/deploy-operator-skill-levels.ts, scripts/deploy-passport-utils.ts, scripts/rewards/deploy-dev-guild-rewards-distributor.ts, scripts/rewards/deploy-ops-guild-rewards-distributor.ts, test/rewards/DevGuildRewardsDistributor.ts, test/rewards/OpsGuildRewardsDistributor.ts
=> Distributing weekly citizen rewards

README.md, scripts/citizens/deploy-discord-usernames.ts, scripts/citizens/deploy-discourse-usernames.ts, scripts/citizens/deploy-github-usernames.ts
=> Deploy Discord/Discourse usernames smart contracts

contracts/package.json
https://www.npmjs.com/package/@nation3/nationcred-contracts?activeTab=versions
=> npm release 0.6.6

contracts/utils/PassportUtils.sol
=> reduce from view to pure

README.md, contracts/NationCred.sol, contracts/citizens/DeveloperSkillLevels.sol, contracts/citizens/DiscordUsernames.sol, contracts/citizens/DiscourseUsernames.sol, contracts/citizens/GitHubUsernames.sol, contracts/citizens/MarketeerSkillLevels.sol, contracts/citizens/OperatorSkillLevels.sol, contracts/package.json, contracts/rewards/DevGuildRewardsDistributor.sol, contracts/rewards/OpsGuildRewardsDistributor.sol, contracts/utils/PassportUtils.sol, package-lock.json, package.json, test/citizens/DiscordUsernames.ts, test/citizens/DiscourseUsernames.ts, test/citizens/GitHubUsernames.ts
=> Require valid passport when setting username (#70)

scripts/citizens/deploy-developer-skill-levels.ts, scripts/citizens/deploy-discord-usernames.ts, scripts/citizens/deploy-discourse-usernames.ts, scripts/citizens/deploy-github-usernames.ts, scripts/citizens/deploy-marketeer-skill-levels.ts, scripts/citizens/deploy-operator-skill-levels.ts, scripts/deploy-nationcred.ts, scripts/helpers.ts, scripts/rewards/deploy-dev-guild-rewards-distributor.ts, scripts/rewards/deploy-ops-guild-rewards-distributor.ts, scripts/utils/deploy-passport-utils.ts
=> fix: skip contract verification on localnet & refactor

README.md
=> 📃 docs: add passport utils address

README.md, deployments/mainnet.json, hardhat.config.ts
=> 🚀 deploy: rewards distributors
